import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import CaseForm from './CaseForm'
import { getAssignableOfficers, getCaseById, getCriminals, getFIRs, updateCase } from '../services/api'

const message = (error, fallback) => error.response?.data?.message || error.response?.data?.error || (error.response ? fallback : 'Unable to reach the CRMS server.')
const formFromRecord = (record) => ({ caseNo: record.caseNo || '', title: record.title || '', description: record.description || '', startDate: record.startDate ? new Date(record.startDate).toISOString().slice(0, 10) : '', status: record.status || 'Open', priority: record.priority || 'Medium', investigationNotes: record.investigationNotes || '', firId: record.firId?._id || record.firId || '', assignedOfficerIds: (record.assignedOfficerIds || []).map((item) => item._id || item), criminalIds: (record.criminalIds || []).map((item) => item._id || item) })

function CaseEdit() {
  const { id } = useParams(); const { logout } = useAuth(); const navigate = useNavigate(); const [record, setRecord] = useState(null); const [options, setOptions] = useState({ firs: [], officers: [], criminals: [] }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { Promise.all([getCaseById(id), getFIRs({ limit: 100 }), getAssignableOfficers(), getCriminals({ limit: 100 })]).then(([caseResponse, firResponse, officerResponse, criminalResponse]) => { const nextRecord = caseResponse.data?.data; setRecord(nextRecord); setOptions({ firs: firResponse.data?.data || [], officers: officerResponse.data?.data || [], criminals: criminalResponse.data?.data || [] }) }).catch((requestError) => setError(message(requestError, 'Unable to load Case for editing.'))).finally(() => setLoading(false)) }, [id])
  const submit = async (form, setFormError) => { try { setSaving(true); await updateCase(id, form); navigate(`/cases/${id}`) } catch (requestError) { setFormError(message(requestError, 'Unable to update case.')) } finally { setSaving(false) } }
  return <div className="dashboard-page"><header className="dashboard-header"><div className="container d-flex align-items-center justify-content-between gap-3 py-3"><div><p className="header-kicker mb-0">CRMS</p><h1 className="header-title mb-0">Edit Case</h1></div><div className="d-flex gap-2"><button className="btn btn-outline-light" onClick={() => navigate(`/cases/${id}`)} type="button">Back to details</button><button className="btn btn-outline-light" onClick={() => { logout(); navigate('/login', { replace: true }) }} type="button">Log out</button></div></div></header><main className="container py-4 py-md-5"><div className="fir-form-card mx-auto" style={{ maxWidth: '980px' }}><p className="eyebrow mb-1">Case record</p><h2 className="section-title mb-3">Edit case</h2>{error && <div className="alert alert-danger" role="alert">{error}</div>}{loading ? <div className="dashboard-state" role="status">Loading case details...</div> : record ? <CaseForm initialForm={formFromRecord(record)} firs={options.firs} officers={options.officers} criminals={options.criminals} loading={saving} submitLabel="Save changes" onSubmit={submit} onCancel={() => navigate(`/cases/${id}`)} /> : null}</div></main></div>
}
export default CaseEdit
